; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 921600
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions-4MB-safeboot.csv
board_build.app_partition_name = app

lib_deps = 
	fastled/FastLED @ ^3.10.3
	thomasfredericks/Bounce2 @ 2.72
	madhephaestus/ESP32Encoder @ 0.12.0
	ESP32Async/AsyncTCP @ ^3.4.10
	ESP32Async/ESPAsyncWebServer @ ^3.11.0
	mathieucarbou/MycilaESPConnect @ ^10.6.0
	mathieucarbou/MycilaSystem @ 4.1.2
	bblanchon/ArduinoJson @ 7.2.2

; environment without OTA for initial flashing or when OTA is not possible
[env:release]
extra_scripts = post:tools/factory.py
custom_safeboot_file = safeboot-esp32dev.bin
; custom_safeboot_url = https://github.com/mathieucarbou/MycilaSafeBoot/releases/download/v3.3.6/safeboot-esp32dev.bin
; custom_safeboot_dir = ../..
build_type = release
build_flags = 

; After initial flashing of the [..].factory.bin, espota can be used for uploading the app
[env:release-ota]
build_type = release
build_flags = 
upload_protocol = espota
upload_port = kaleidoscope.local
custom_safeboot_restart_path = /api/safeboot
extra_scripts = tools/safeboot.py

[env:debug-ota]
build_type = debug
build_flags = 
	-D DEBUG
upload_protocol = espota
upload_port = kaleidoscope.local
custom_safeboot_restart_path = /api/safeboot
extra_scripts = tools/safeboot.py

[env:JTAG]
build_type = debug
debug_tool = esp-prog
upload_protocol = esp-prog
debug_init_break = tbreak setup
debug_speed = 20000
; The debug_build_flags line below causes the error: undefined reference to `vtable for fs::FileImpl'
; https://github.com/platformio/platform-espressif32/issues/1238
debug_build_flags = -O0 -g -ggdb
build_flags = 
	-D DEBUG
	-D JTAG
